### ISSUE TITLE
Question: How to connect to the container to download the world backup?

### ISSUE THREAD

**Issue by vitorfranca** [rileydakota/valheim-ecs-fargate-cdk#12]

**Comment by rileydakota** [comment]
Hi there @vitorfranca - thanks for using the solution! I would recommend using AWS Transfer Family - there is a discussion of getting this working in the issue here: https://github.com/rileydakota/valheim-ecs-fargate-cdk/issues/1#issuecomment-781695616

See also : https://aws.amazon.com/blogs/aws/new-aws-transfer-family-support-for-amazon-elastic-file-system/

AWS Transfer Family would essentially give you a way to connect to the EFS Volume where the mapfile is stored via SFTP and not need to launch an EC2 Instance. Just don't forget to delete the Transfer Family Server, as it is a bit expensive (0.30/hr) but not a huge deal provided you shut it off.

**Comment by vitorfranca** [comment]
Hey @rileydakota, thanks for the super quick answer! 

I was able to do it. 
I think the easiest way is to create an EC2 instance and mount the server's EFS and scp from my computer to the instance.

and that did it!

**Comment by blysik** [comment]
> Hey @rileydakota, thanks for the super quick answer!
> 
> I was able to do it.
> I think the easiest way is to create an EC2 instance and mount the server's EFS and scp from my computer to the instance.
> 
> and that did it!

Howdy @vitorfranca !  Any chance you could do a quick writeup of how you did this?
