### ISSUE TITLE
Next steps? IP address/connect to server questions

### ISSUE THREAD

**Issue by rossvz** [rileydakota/valheim-ecs-fargate-cdk#3]
Hey there! I'm fairly inexperienced with AWS in general, but definitely haven't used ECS and CDK before!

I have ran the deployment script and I can see the container and stuff in ECS console. I think I'm missing a conceptual step - is this actually running the container and instance, or just creating the container image? Is there a manual step that needs to happen after the deploy? 

If I go into ECS console -> Clusters I can see the Service and Task defined, but nothing under ECS Instances: 
![image](https://user-images.githubusercontent.com/9866589/108527190-ff170f80-729f-11eb-92dd-88eae07434f5.png)

**Comment by rileydakota** [comment]
Hey there! Thanks for using the solution! So the code is actually pulling down https://github.com/lloesche/valheim-server-docker and running it using AWS ECS. Because we are using ECS Fargate - there is no actual "Instance" to manage. The solution assigns a public IP to the "task" (basically instructions and a template to run the valheim server docker image). You can see that by clicking on `Tasks`, clicking the task ID in the first column, and then looking for Public IP on the next page. 
![Screen Shot 2021-02-19 at 11 16 27 AM](https://user-images.githubusercontent.com/73837129/108530736-ef99c580-72a3-11eb-920b-77e26542844a.png)

I will try to add some better documentation shortly that covers this. I will also look into capability for adding a Domain Name to the solution.

**Comment by rossvz** [comment]
Nice!! That's perfect. Got the IP 👍 

Wonder if there's a way to get that programmatically with AWS cli and print to the console?

**Comment by rileydakota** [comment]
@rossvz I did look into trying to add it as a CloudFormation stack output - but didn't have much luck. The CLI command option is an interesting idea. I will look into that - maybe the CDK has some sort of "post deploy" functionality? Otherwise we could add the CLI command to the readme (feel free to PR :) - otherwise I will try and get to it this weekend). Thanks again for opening this issue!
